<a href="https://colab.research.google.com/github/mmaruthi/IITJML/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Step to upload the csv data given in Assignment
from google.colab import files 
uploaded = files.upload()

Saving dataset - Sheet1.csv to dataset - Sheet1.csv


In [ ]:
#Import the basic libraries 
import numpy as np 
import pandas as pd 

#create a data frame readinf this file 
df=pd.read_csv("dataset - Sheet1.csv")

In [ ]:
#check the shape of the dataset 
df.shape

(160, 2)

In [ ]:
#See couple of rows to get an idea
df.head()

Predicted Class  Actual Class
0                0             0
1                0             0
2                1             0
3                0             0
4                0             0

In [ ]:
#let us see the column names
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Predicted Class  160 non-null    int64
 1   Actual Class     160 non-null    int64
dtypes: int64(2)
memory usage: 2.6 KB


In [ ]:
# Let us see how many multiple classes are present in this 
classes = df['Predicted Class'].unique()
classes

array([0, 1, 2, 3])

In [ ]:
#True Positive -- No. of predictions equal to the actual values
Truepositive = df[df['Actual Class'] == df['Predicted Class']]
Truepositive.head()

Predicted Class  Actual Class
0                0             0
1                0             0
3                0             0
4                0             0
8                0             0

In [ ]:
#let us see how many are correctly predicted 
Truepositive.shape

(121, 2)

**2.a**

In [ ]:
#Accuracy = Correct Predictons / Total Predictions (or) [True Positive + True Negative] / Total Predictions
Accuracy = 121/160
Accuracy

0.75625

In [ ]:
#Let's calculate the True positive for each class 

tp0 = df[(df['Actual Class'] ==0) & (df['Predicted Class'] ==0)]
tp1 = df[(df['Actual Class'] ==1) & (df['Predicted Class'] ==1)]
tp2 = df[(df['Actual Class'] ==2) & (df['Predicted Class'] ==2)]
tp3 = df[(df['Actual Class'] ==3) & (df['Predicted Class'] ==3)]

print("True positive for class 0 =", tp0.shape)
print("True positive for class 1 =", tp1.shape)
print("True positive for class 2 =", tp2.shape)
print("True positive for class 3 =", tp3.shape)

True positive for class 0 = (33, 2)
True positive for class 1 = (32, 2)
True positive for class 2 = (29, 2)
True positive for class 3 = (27, 2)


In [ ]:
# Class wise accuracy 
# to get class wise accuracy , let's see how many does each class belong to with actual class values 
tp0a = df[(df['Actual Class'] ==0)]
tp1a = df[(df['Actual Class'] ==1)]
tp2a = df[(df['Actual Class'] ==2)]
tp3a = df[(df['Actual Class'] ==3)]

print ("Actual Entries in class 0" , tp0a.shape)
print ("Actual Entries in class 1" , tp1a.shape)
print ("Actual Entries in class 2" , tp2a.shape)
print ("Actual Entries in class 3" , tp3a.shape)

Actual Entries in class 0 (49, 2)
Actual Entries in class 1 (36, 2)
Actual Entries in class 2 (40, 2)
Actual Entries in class 3 (35, 2)


In [ ]:
#To get class wise accuracy 
acc0 = 33/49
acc1 = 32/36
acc2 = 29/40
acc3 = 27/35

print ("class 0 accuracy" , acc0)
print ("class 1 accuracy" , acc1)
print ("class 2 accuracy" , acc2)
print ("class 3 accuracy" , acc3)

class 0 accuracy 0.673469387755102
class 1 accuracy 0.8888888888888888
class 2 accuracy 0.725
class 3 accuracy 0.7714285714285715


**2.b - Confusion matrix**

In [ ]:
# To Draw confusion matrix lets calculate the misclassifications 

# actual class 0 predicted as class 1,2,3
tp01=df[(df['Actual Class'] ==0) & (df['Predicted Class']==1)]
print(tp01.shape)
tp02=df[(df['Actual Class'] ==0) & (df['Predicted Class']==2)]
print(tp02.shape)
tp03=df[(df['Actual Class'] ==0) & (df['Predicted Class']==3)]
print(tp03.shape)

(8, 2)
(4, 2)
(4, 2)


In [ ]:

# actual class 1 predicted as class 0,2,3
tp10=df[(df['Actual Class'] ==1) & (df['Predicted Class']==0)]
print(tp10.shape)
tp12=df[(df['Actual Class'] ==1) & (df['Predicted Class']==2)]
print(tp12.shape)
tp13=df[(df['Actual Class'] ==1) & (df['Predicted Class']==3)]
print(tp13.shape)

(1, 2)
(3, 2)
(0, 2)


In [ ]:

# actual class 2 predicted as class 0,1,3
tp20=df[(df['Actual Class'] ==2) & (df['Predicted Class']==0)]
print(tp20.shape)
tp22=df[(df['Actual Class'] ==2) & (df['Predicted Class']==1)]
print(tp22.shape)
tp23=df[(df['Actual Class'] ==2) & (df['Predicted Class']==3)]
print(tp23.shape)

(3, 2)
(2, 2)
(6, 2)


In [ ]:
# actual class 3 predicted as class 0,1,2
tp30=df[(df['Actual Class'] ==3) & (df['Predicted Class']==0)]
print(tp30.shape)
tp31=df[(df['Actual Class'] ==3) & (df['Predicted Class']==1)]
print(tp31.shape)
tp32=df[(df['Actual Class'] ==3) & (df['Predicted Class']==2)]
print(tp32.shape)

(2, 2)
(3, 2)
(3, 2)


SO Now the confusion matrix is as below :
Predicted 

In [ ]:
predicted
               0   1   2   3
          
           0   33  8   4   4
           
           1   1   32  3   0
 actual          
           2   3   2   29  6
           
           3   2   3   3   27

2.**c** **bold text**

Class 0

In [ ]:
predicted
               0   1   2   3
          
           0   33  8   4   4
           
           1   1   32  3   0
 actual          
           2   3   2   29  6
           
           3   2   3   3   27

In [ ]:
tp0=33
tn0=32+3+2+3+29+6+3+27
fp0=1+3+2
fn0=8+4+4

In [ ]:
# precision and recall of class 0
precision0=tp0/(tp0+fp0)
print(precision0)
recall0=tp0/(tp0+fn0)
print(recall0)

0.8461538461538461
0.673469387755102


Class **1**

In [ ]:
predicted
               0   1   2   3
          
           0   33  8   4   4
           
           1   1   32  3   0
 actual          
           2   3   2   29  6
           
           3   2   3   3   27

In [ ]:
tp1=32
tn1=33+4+4+3+2+29+6+27+3
fp1=8+2+3
fn1=1+3+0

In [ ]:
# precision and recall of class 1
precision1=tp1/(tp1+fp1)
print(precision1)
recall1=tp1/(tp1+fn1)
print(recall1)

0.7111111111111111
0.8888888888888888


**Class 2**

In [ ]:
predicted
               0   1   2   3
          
           0   33  8   4   4
           
           1   1   32  3   0
 actual          
           2   3   2   29  6
           
           3   2   3   3   27

In [ ]:
tp2=29
tn2=33+8+4+1+32+0+2+3+27
fp2=4+3+3
fn2=3+2+6

In [ ]:
# precision and recall of class 2
precision2=tp2/(tp2+fp2)
print(precision2)
recall2=tp2/(tp2+fn2)
print(recall2)

0.7435897435897436
0.725


In [ ]:
tp3=27
tn3=33+8+4+1+32+3+3+2+29
fp3=4+0+6
fn3=2+3+3

In [ ]:
# precision and recall of class 3
precision3=tp3/(tp3+fp3)
print(precision3)
recall3=tp3/(tp3+fn3)
print(recall3)

0.7297297297297297
0.7714285714285715


In [ ]:
#Macro Average =  mean average precision/recall of all classes.

macro_avg_precision=(precision0+precision1+precision2+precision3)/4
macro_avg_precision

0.7576461076461076

In [ ]:
macro_avg_recall=(recall0+recall1+recall2+recall3)/4
macro_avg_recall

0.7646967120181406

In [ ]:
#Weighted_avg = The weights for each class are the total number of samples of that class
weighted_avg_precision=(precision0*49+precision1*36+precision2*38+precision3*35)/(49+36+38+35)
weighted_avg_precision

0.7649271472056283

In [ ]:
weighted_avg_recall=(recall0*49+recall1*36+recall2*38+recall3*35)/(49+36+38+35)
weighted_avg_recall

0.7566455696202532

F-1 Score 

2.d  

In [ ]:
class0_f1=2*(precision0*recall0)/(precision0+recall0)
print("F1 for class 0", class0_f1)

class1_f1=2*(precision1*recall1)/(precision1+recall1)
print("F1 for class 1", class1_f1)

class2_f1=2*(precision2*recall2)/(precision2+recall2)
print("F1 for class 2" ,class2_f1)

class3_f1=2*(precision3*recall3)/(precision3+recall3)
print("F1 for class 3" ,class3_f1)

F1 for class 0 0.75
F1 for class 1 0.7901234567901234
F1 for class 2 0.7341772151898733
F1 for class 3 0.75


2.e 
Type I and Type II error 

In [ ]:
class0_type_1=fp0/(fp0+tn0)
print("class 0 type 1 error", class0_type_1*100)
class0_type_2=fn0/(fn0+tp0)
print("class 0 type 2 error", class0_type_2*100)

class1_type_1=fp1/(fp1+tn1)
print("Class 1 type 1 error", class1_type_1*100)
class1_type_2=fn1/(fn1+tp1)
print("class 1 type 2 error", class1_type_2*100)

class2_type_1=fp2/(fp2+tn2)
print("class 2 type 1 error", class2_type_1*100)
class2_type_2=fn2/(fn2+tp2)
print("class 2 type 2 error", class2_type_2*100)

class3_type_1=fp3/(fp3+tn3)
print("class 3 type 1 error", class3_type_1*100)
class3_type_2=fn3/(fn3+tp3)
print("class 3 type 2 error", class3_type_2*100)

class 0 type 1 error 5.405405405405405
class 0 type 2 error 32.6530612244898
Class 1 type 1 error 10.483870967741936
class 1 type 2 error 11.11111111111111
class 2 type 1 error 8.333333333333332
class 2 type 2 error 27.500000000000004
class 3 type 1 error 8.0
class 3 type 2 error 22.857142857142858


In [ ]:

y_test = df['Actual Class']
y_pred = df['Predicted Class']


#importing confusion matrix
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test, y_pred)
print('Confusion Matrix\n')
print(confusion)

#importing accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred)))


print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_test, y_pred, target_names=['Class 0','Class 1', 'Class 2', 'Class 3']))

Confusion Matrix

[[33  8  4  4]
 [ 1 32  3  0]
 [ 3  2 29  6]
 [ 2  3  3 27]]

Accuracy: 0.76

Macro Precision: 0.76
Macro Recall: 0.76
Macro F1-score: 0.76

Weighted Precision: 0.76
Weighted Recall: 0.76
Weighted F1-score: 0.76

Classification Report

              precision    recall  f1-score   support

     Class 0       0.85      0.67      0.75        49
     Class 1       0.71      0.89      0.79        36
     Class 2       0.74      0.72      0.73        40
     Class 3       0.73      0.77      0.75        35

    accuracy                           0.76       160
   macro avg       0.76      0.76      0.76       160
weighted avg       0.76      0.76      0.76       160



In [ ]:
Comparison Report                                                 



              precision_sklearn/standard   recall_sklearn/standard  f1-score_sklearn/standard    

     Class 0       0.85/.85                          0.67/.67                      0.75/.75        
     Class 1       0.71/.71                          0.89/.89                      0.79/.79        
     Class 2       0.74/.74                         0.72/.72                      0.73/.73        
     Class 3       0.73/.73                         0.77/.77                      0.75/.75         

    accuracy                           0.76/.75        
   macro avg       0.76/.76      0.76/.76      0.76/.76        
weighted avg       0.76/.76      0.76/.76      0.76/.76